#数据库连接
spring: 

    datasource: 
        url: jdbc:mysql://localhost:9999/parksys?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
          prefix: /WEB-INF/jsp/
          suffix: .jsp
#服务器端口
server: 
  port: 8080
  